### ISSUE TITLE
提供的下载并不是0.7.4的oc

### ISSUE THREAD

**Issue by burst3166** [SamCsquared/Deskmini-H470-OpenCore-EFI#2]
试了几次，发现仍是0.73的oc，然后自己去oc官网下了0.74的自己替换才正常

**Comment by SamCsquared** [comment]
感谢您的回报，最近才刚用Github不太熟，应该是上传的档案没更新到，不过现在出差也没办法好好处理，查看了一下应该是BOOTx64.efi的问题，我重传了您看看
