### ISSUE TITLE
加装侧面USB2.0扩展后无法识别

### ISSUE THREAD

**Issue by MarxD** [SamCsquared/Deskmini-H470-OpenCore-EFI#3]
是因为超过15个USB端口的限制了吗？，我算了一下，后置5加前置2，3.0+2.0，乘以2，7x2=14再加个蓝牙刚好15，想用侧面的是不是只能屏蔽掉部分2.0端口了。。

**Comment by SamCsquared** [comment]
您好，这个答案是不一定，苹果的逻辑是一个控制器只能有15个接口，因为我没有购买侧面USB，侧面USB也只有2.0，所以无法得知华擎这个主机板是不是有另外一个USB的控制器，但我猜大概是没有所以的确是需要牺牲其他孔的2.0
